import os
import sys
import json
import time

# YouTube Data API v3 Uploader
# Requirements: pip install google-api-python-client google-auth-oauthlib google-auth-httplib2

def get_authenticated_service(client_secrets_file="client_secrets.json", token_file="token.json"):
    from googleapiclient.discovery import build
    from google.oauth2.credentials import Credentials
    from google_auth_oauthlib.flow import InstalledAppFlow

    SCOPES = [
        "https://www.googleapis.com/auth/youtube.upload",
        "https://www.googleapis.com/auth/youtube.force-ssl"
    ]

    creds = None
    if os.path.exists(token_file):
        creds = Credentials.from_authorized_user_file(token_file, SCOPES)
    
    if not creds or not creds.valid:
        if os.path.exists(client_secrets_file):
            flow = InstalledAppFlow.from_client_secrets_file(client_secrets_file, SCOPES)
            creds = flow.run_local_server(port=0)
            with open(token_file, "w") as token:
                token.write(creds.to_json())
        else:
            print(f"[!] {client_secrets_file} not found. Please provide Google Cloud OAuth credentials.")
            return None

    return build("youtube", "v3", credentials=creds)

def upload_video(video_path, thumbnail_path=None, title=None, description=None, tags=None, privacy_status="public"):
    from googleapiclient.http import MediaFileUpload

    print("=" * 65)
    print("           YOUTUBE AUTO-UPLOADER")
    print("=" * 65)
    print(f"Video file: {video_path}")
    print(f"Thumbnail:  {thumbnail_path}")
    print(f"Privacy:    {privacy_status}")

    youtube = get_authenticated_service()
    if not youtube:
        print("[!] YouTube authentication failed or credentials missing.")
        print("[*] Video and thumbnail are saved locally and ready for upload.")
        return None

    if title is None:
        title = "Stockfish 19 (3600+ ELO) Grandmaster Battle | Sicilian Defense"
    
    if tags is None:
        tags = ["Chess", "Stockfish", "Grandmaster", "Sicilian Defense", "Chess AI", "Chess Tactics", "Rapid Chess"]

    body = {
        "snippet": {
            "title": title,
            "description": description or "Autonomous Grandmaster Chess Match generated by Stockfish 19 with real-time tactical commentary.",
            "tags": tags,
            "categoryId": "20" # Gaming category
        },
        "status": {
            "privacyStatus": privacy_status,
            "selfDeclaredMadeForKids": False
        }
    }

    media = MediaFileUpload(video_path, chunksize=-1, resumable=True, mimetype="video/mp4")
    print(f"[*] Uploading \"{title}\" to YouTube...")
    
    request = youtube.videos().insert(part=",".join(body.keys()), body=body, media_body=media)
    response = None
    while response is None:
        status, response = request.next_chunk()
        if status:
            print(f"  -> Upload progress: {int(status.progress() * 100)}%")

    video_id = response.get("id")
    print(f"[+] Video successfully uploaded! Video URL: https://youtu.be/{video_id}")

    # Set custom thumbnail if provided
    if thumbnail_path and os.path.exists(thumbnail_path) and video_id:
        print(f"[*] Uploading custom thumbnail: {thumbnail_path}...")
        try:
            youtube.thumbnails().set(
                videoId=video_id,
                media_body=MediaFileUpload(thumbnail_path, mimetype="image/png")
            ).execute()
            print("[+] Custom thumbnail uploaded successfully!")
        except Exception as e:
            print(f"[!] Thumbnail upload note: {e}")

    return video_id

if __name__ == "__main__":
    base_dir = os.path.dirname(os.path.abspath(__file__))
    vid = os.path.join(base_dir, "recordings", "grandmaster_chess_battle.mp4")
    thumb = os.path.join(base_dir, "recordings", "thumbnail.png")
    upload_video(vid, thumbnail_path=thumb, privacy_status="unlisted")
